import './globals.css'
import { ReactNode } from 'react'
import { Roboto } from 'next/font/google'

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  weight: ['400', '500', '700', '900'],
})

export const metadata = {
  title: 'Gabriel.dev',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} bg-gray-900`}>{children}</body>
    </html>
  )
}
